/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SIMVENT;


import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.Parent;
public class App extends Application{

@Override // Her bliver MainScreenView instantieret og den styres gennem MainScreenCtrl
public void start(Stage primaryStage) throws Exception {
    Parent mainScreen = FXMLLoader.load(getClass().getResource("/MainScreenView.fxml"));
    primaryStage.setTitle("Main Screen");
    primaryStage.setScene(new Scene(mainScreen));
    primaryStage.show();
}

public static void main(String[] args) {
 
    
   launch(args);
}
}




